/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wpass
 */
public class Editar_Evento extends javax.swing.JFrame {

    /**
     * Creates new form Editar_Evento
     */
    public Editar_Evento() {
        initComponents();
    }
    
public void c(String sql){
        try {
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/EventFlow", "root", "");
            PreparedStatement teste = (PreparedStatement) con.prepareStatement(sql);
            teste.execute();
            
            ResultSet resultado = teste.executeQuery(sql);
            
            DefaultTableModel model = (DefaultTableModel) c.getModel();
            model.setNumRows(0);
            
            while(resultado.next())
            {    
                model.addRow(new Object[]
                {
                    resultado.getString("TituloEvento"),
                    resultado.getString("TipoEvento"),
                    resultado.getString("DataEvento_inicial")
                });
            }
            teste.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Visualização_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_visualizar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        c = new javax.swing.JTable();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_visualizar.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_visualizar.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_visualizar.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_visualizar.setText("EDITAR");
        getContentPane().add(jlbl_visualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 60));

        c.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Tipo", "Data"
            }
        ));
        c.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(c);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 370, 200));

        background.setBackground(new java.awt.Color(135, 79, 255));
        background.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        background.setForeground(new java.awt.Color(135, 79, 255));
        background.setText("EVENTO");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpnl_fundo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cAncestorAdded
        // TODO add your handling code here:
        this.c("SELECT * FROM Evento ORDER BY TituloEvento DESC");
    }//GEN-LAST:event_cAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar_Evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTable c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbl_visualizar;
    // End of variables declaration//GEN-END:variables

    private void jScrollPane2(String select__from_Evento_ORDER_BY_TituloEvento) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
