/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wpass
 */
public class Visualização_Evento extends javax.swing.JFrame {

    /**
     * Creates new form Visualização_Evento
     */
    public Visualização_Evento() {
        initComponents();
    }
    
    public void jTable1(String sql){
        try {
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/EventFlow", "root", "");
            PreparedStatement statement = (PreparedStatement) con.prepareStatement(sql);
            statement.execute();
            
            ResultSet resultado = statement.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);
            
            while(resultado.next()){
                model.addRow(new Object[]
                {
                    resultado.getString("TituloEvento"),
                    resultado.getString("TipoEvento"),
                    resultado.getString("DataEvento_inicial")  
                });
            }
             statement.close();
             con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Visualização_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jlbl_IMG_Evento = new javax.swing.JLabel();
        jlbl_visualizar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jtxt_titulo = new javax.swing.JTextField();
        jtxt_tipoEvento = new javax.swing.JTextField();
        jtxt_contatoEvento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlbl_visualizar1 = new javax.swing.JLabel();
        jlbl_IMG_Evento1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbl_visualizar2 = new javax.swing.JLabel();
        jlbl_IMG_Evento2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jtxt_statusEvento = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jlbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(110, 21, 189));
        jButton2.setForeground(new java.awt.Color(110, 21, 189));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, 50, 30));

        jlbl_IMG_Evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_IMG_Evento.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_IMG_Evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_IMG_Evento.setText("EVENTO");
        getContentPane().add(jlbl_IMG_Evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 180, 60));

        jlbl_visualizar.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_visualizar.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_visualizar.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_visualizar.setText("VISUALIZAR");
        getContentPane().add(jlbl_visualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 270, 60));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Eventos Cadastrados");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 206, -1, 30));

        jButton6.setBackground(new java.awt.Color(129, 25, 184));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 150, 60));

        jLabel11.setText("Editar Evento");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 210, -1, 20));

        jButton4.setBackground(new java.awt.Color(129, 25, 184));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 130, 60));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 150, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 210, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cadastrar Evento");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, 40));

        jButton1.setBackground(new java.awt.Color(129, 25, 184));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, 30, -1));

        jButton5.setBackground(new java.awt.Color(129, 25, 184));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 130, 60));

        jtxt_titulo.setText("TituloEvento");
        getContentPane().add(jtxt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, -1));

        jtxt_tipoEvento.setText("TipoEvento");
        getContentPane().add(jtxt_tipoEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, -1));

        jtxt_contatoEvento.setText("Contato_Evento");
        jtxt_contatoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_contatoEventoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_contatoEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 150, -1));

        jLabel2.setText("Meio de contato");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 150, 20));

        jlbl_visualizar1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_visualizar1.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_visualizar1.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_visualizar1.setText("VISUALIZAR");
        getContentPane().add(jlbl_visualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 270, 60));

        jlbl_IMG_Evento1.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_IMG_Evento1.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_IMG_Evento1.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_IMG_Evento1.setText("EVENTO");
        getContentPane().add(jlbl_IMG_Evento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 180, 60));

        jLabel5.setText("Tipo do evento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 150, 20));

        jLabel4.setText("Nome do evento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 130, -1));

        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jlbl_visualizar2.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_visualizar2.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_visualizar2.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_visualizar2.setText("EVENTOS");
        getContentPane().add(jlbl_visualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 220, 40));

        jlbl_IMG_Evento2.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_IMG_Evento2.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_IMG_Evento2.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_IMG_Evento2.setText("PRÓXIMOS");
        getContentPane().add(jlbl_IMG_Evento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 530, 230, 40));

        jLabel7.setText("Data");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel8.setText("Data");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel12.setText("Fornecedor");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Tipo", "Data", "Fornecedor"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 450, 90));

        jTextField2.setText("Fornecedor Relacionado");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 150, -1));

        jtxt_statusEvento.setText("Data do evento");
        jtxt_statusEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_statusEventoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_statusEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, -1));

        jTextField3.setText("ID do evento");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 150, -1));

        jPanel1.setBackground(new java.awt.Color(129, 25, 184));

        jLabel3.setText("Pesquisar Evento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 310, 20));

        jlbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event.jpg"))); // NOI18N
        getContentPane().add(jlbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

          
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        Editar_Evento ee = new Editar_Evento();
        ee.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tabela_visualizarEvento tv = new tabela_visualizarEvento();
        tv.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Connection con = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/EventFlow";
            String user = "root";
            String password = "";
            
            con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT TituloEvento, TipoEvento, Contato_Evento, DataEvento_inicial, ID_Evento FROM Evento WHERE TituloEvento = ?"; 
            
            statement = con.prepareStatement(sql);
            statement.setString(1, jTextField1.getText());
            
            ResultSet resultset = statement.executeQuery();
            if(resultset.next()){
                
                String TituloEvento = resultset.getString("TituloEvento");
                jtxt_titulo.setText(TituloEvento);
                
                String TipoEvento = resultset.getString("TipoEvento");
                jtxt_tipoEvento.setText(TipoEvento);
                        
                String Contato_Evento = resultset.getString("Contato_Evento");
                jtxt_contatoEvento.setText(Contato_Evento);
                        
                String DataEvento_inicial = resultset.getString("DataEvento_inicial");
                jtxt_statusEvento.setText(DataEvento_inicial);
                
                String ID_Evento = resultset.getString("ID_Evento");
                jTextField3.setText(ID_Evento);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Titulo de evento não encontrado.");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Visualização_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxt_contatoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_contatoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_contatoEventoActionPerformed

    private void jtxt_statusEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_statusEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_statusEventoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cadastro_evento ce = new cadastro_evento();
        ce.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
        this.jTable1("SELECT * FROM Evento ORDER BY DataEvento_inicial DESC LIMIT 3");
    }//GEN-LAST:event_jTable1AncestorAdded

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualização_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualização_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualização_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualização_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualização_Evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jlbl_IMG_Evento;
    private javax.swing.JLabel jlbl_IMG_Evento1;
    private javax.swing.JLabel jlbl_IMG_Evento2;
    private javax.swing.JLabel jlbl_background;
    private javax.swing.JLabel jlbl_visualizar;
    private javax.swing.JLabel jlbl_visualizar1;
    private javax.swing.JLabel jlbl_visualizar2;
    private javax.swing.JTextField jtxt_contatoEvento;
    private javax.swing.JTextField jtxt_statusEvento;
    private javax.swing.JTextField jtxt_tipoEvento;
    private javax.swing.JTextField jtxt_titulo;
    // End of variables declaration//GEN-END:variables

    private void Tabela_visualizarEvento() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void visualizarEvento(String sql) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
