/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wpass
 */
public class EditarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form EditarFornecedor
     */
    public EditarFornecedor() {
        initComponents();
    }
 
    public void Jtbl(String sql){
        try {
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/EventFlow", "root", "");
            PreparedStatement teste = (PreparedStatement) con.prepareStatement(sql);
            teste.execute();
            
            ResultSet resultado = teste.executeQuery(sql);
            
            DefaultTableModel model = (DefaultTableModel) Jtbl.getModel();
            model.setNumRows(0);
            
            while(resultado.next())
            {    
                model.addRow(new Object[]
                {
                    resultado.getString("Nome"),
                    resultado.getString("Email_Fornecedor"),
                    resultado.getString("CEPfornecedor"),
                    resultado.getString("Servicos"),
                    resultado.getString("StatusFornecedorGeral")
                });
            }
            teste.close();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Visualização_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        status1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        servicos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        id_fornecedor = new javax.swing.JTextField();
        cepfornecedor = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(135, 79, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Serviços");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 20));

        jLabel4.setBackground(new java.awt.Color(135, 79, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Insira o ID do fornecedor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, -1));

        jLabel8.setBackground(new java.awt.Color(135, 79, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nome");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 360, -1));

        jLabel10.setBackground(new java.awt.Color(135, 79, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, 20));

        jLabel7.setBackground(new java.awt.Color(135, 79, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 20));
        getContentPane().add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 360, -1));

        jLabel11.setBackground(new java.awt.Color(135, 79, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, 20));
        getContentPane().add(servicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 360, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(135, 79, 255));
        jLabel3.setText("FORNECEDOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 280, 50));

        jButton2.setBackground(new java.awt.Color(135, 79, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 90, 20));

        jLabel9.setBackground(new java.awt.Color(135, 79, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CEP");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 20));

        id_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_fornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(id_fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 360, -1));

        cepfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepfornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(cepfornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 360, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 360, -1));

        jButton1.setBackground(new java.awt.Color(135, 79, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 40, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EDITAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, -1));

        Jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Email", "Nome", "Email", "Status", "Serviços"
            }
        ));
        Jtbl.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JtblAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Jtbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 390, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpnl_fundo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void JtblAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JtblAncestorAdded
        // TODO add your handling code here:
        this.Jtbl("SELECT * FROM Fornecedor ORDER BY Nome DESC");        
    }//GEN-LAST:event_JtblAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Connection conexao = null;
            PreparedStatement statement = null;

            String url = "jdbc:mysql://localhost:3306/EventFlow";
            String user = "root";
            String password = "";

            conexao = DriverManager.getConnection(url, user, password);
            String sql = "SELECT ID_Fornecedor, Nome, Email_Fornecedor, CEPfornecedor, Servicos, StatusFornecedorGeral FROM Fornecedor WHERE ID_Fornecedor = ?";

            statement = conexao.prepareStatement(sql);
            statement.setString(1, id_fornecedor.getText());
            // statement.setInt(1, Integer.parseInt(jTextField1.getText()));

            ResultSet resultSet =  statement.executeQuery();
            if(resultSet.next()){

                //inserir o id tmb no jtext de

                String ID_Fornecedor = resultSet.getString("ID_Fornecedor");
                id_fornecedor.setText(ID_Fornecedor);

                String Nome = resultSet.getString("Nome");
                jTextField1.setText(Nome);

                String Email_Fornecedor = resultSet.getString("Email_Fornecedor");
                jTextField3.setText(Email_Fornecedor);

                String CEPfornecedor = resultSet.getString("CEPfornecedor");
                cepfornecedor.setText(CEPfornecedor);

                String Servicos = resultSet.getString("Servicos");
                servicos.setText(Servicos);

                String StatusFornecedorGeral = resultSet.getString("StatusFornecedorGeral");
                id.setText(StatusFornecedorGeral);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Fornecedor não encontrado. tente novamente.");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Editar_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_fornecedorActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void cepfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepfornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepfornecedorActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            // TODO add your handling code here:
            Connection conexao = null;
            PreparedStatement statement = null;

            String url = "jdbc:mysql://localhost:3306/EventFlow";
            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection(url, usuario, senha);
            String sql = "UPDATE Fornecedor SET Nome = ?, Email_Fornecedor = ?, CEPfornecedor = ?, Servicos = ?, StatusFornecedorGeral = ? WHERE ID_Fornecedor = ?";
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jTextField1.getText());
            statement.setString(2, jTextField3.getText());
            statement.setString(3, cepfornecedor.getText());
            statement.setString(4, servicos.getText());
            statement.setString(5, status1.getText());
            statement.setString(6, id.getText());

            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro atualizado!");
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Editar_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtbl;
    private javax.swing.JTextField cepfornecedor;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id_fornecedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField servicos;
    private javax.swing.JTextField status1;
    // End of variables declaration//GEN-END:variables

    private void Jtbl() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
