/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author marci
 */
public class modelo_evento extends javax.swing.JFrame {
    /**
     * Creates new form add_evento
     */
    public modelo_evento() {
        initComponents();
    }
    
    public static modelo_evento telaAnterior;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_codigo_modelo_evento = new javax.swing.JLabel();
        jtxtf_codigo_modelo_evento = new javax.swing.JTextField();
        jlbl_nome_modelo_evento = new javax.swing.JLabel();
        jtxtf_nome_modelo_evento = new javax.swing.JTextField();
        jlbl_coordenador_esponsavel = new javax.swing.JLabel();
        jtxtf_coordenador_responsavel = new javax.swing.JTextField();
        jlbl_Contato = new javax.swing.JLabel();
        jtxtf_Contato = new javax.swing.JTextField();
        jlbl_Publico = new javax.swing.JLabel();
        jcbx_Publico = new javax.swing.JComboBox<>();
        jlbl_locais_de_realizacao = new javax.swing.JLabel();
        jcbx_locais_de_realizacao = new javax.swing.JComboBox<>();
        jlbl_Dt_Inicial = new javax.swing.JLabel();
        jtxtf_Dt_Inicial = new javax.swing.JTextField();
        jlbl_Dt_Termino = new javax.swing.JLabel();
        jtxtf_Dt_Termino = new javax.swing.JTextField();
        jlbl_descricao_modelo_evento = new javax.swing.JLabel();
        jsclp_Descricao = new javax.swing.JScrollPane();
        jtxta_descricao_modelo_evento = new javax.swing.JTextArea();
        jlbl_logradouro_modelo_evento = new javax.swing.JLabel();
        jtxtf_logradouro_modelo_evento = new javax.swing.JTextField();
        jlbl_numero_modelo_evento = new javax.swing.JLabel();
        jtxtf_numero_modelo_evento = new javax.swing.JTextField();
        jlbl_complemento_modelo_evento = new javax.swing.JLabel();
        jtxtf_complemento_modelo_evento = new javax.swing.JTextField();
        jlbl_bairro_modelo_evento = new javax.swing.JLabel();
        jtxtf_bairro_modelo_evento = new javax.swing.JTextField();
        jlbl_cidade_modelo_evento = new javax.swing.JLabel();
        jtxtf_cidade_modelo_evento = new javax.swing.JTextField();
        jlbl_uf_modelo_evento = new javax.swing.JLabel();
        jtxtf_uf_modelo_evento = new javax.swing.JTextField();
        jlbl_cep_modelo_evento = new javax.swing.JLabel();
        jtxtf_cep_modelo_evento = new javax.swing.JTextField();
        jlbl_img_logo_EF = new javax.swing.JLabel();
        jlbl_txt_modelo_evento = new javax.swing.JLabel();
        jlbl_img_txt_modelo_evento = new javax.swing.JLabel();
        jlbl_txt_de_evento = new javax.swing.JLabel();
        jlbl_btn_excluir_modelo_evento = new javax.swing.JLabel();
        jlbl_btn_buscar_modelo_evento = new javax.swing.JLabel();
        jlbl_qtd_participante = new javax.swing.JLabel();
        jcbx_qtd_participante = new javax.swing.JComboBox<>();
        jlbl_itens_servicos = new javax.swing.JLabel();
        jcbx_itens_servicos = new javax.swing.JComboBox<>();
        jlbl_local_modelo_evento = new javax.swing.JLabel();
        jckb_c_local_modelo_evento1 = new javax.swing.JCheckBox();
        jckb_s_local_modelo_evento = new javax.swing.JCheckBox();
        jlbl_nome_local_modelo_evento = new javax.swing.JLabel();
        jtxtf_nome_local_modelo_evento = new javax.swing.JTextField();
        Jbtn_novo_modelo_evento = new java.awt.Button();
        Jbtn_editar_modelo_evento = new java.awt.Button();
        Jbtn_excluir_modelo_evento = new java.awt.Button();
        jbtn_voltar_dashboard = new javax.swing.JButton();
        jbtn_inserir_imagem_modelo_evento = new javax.swing.JToggleButton();
        jlbl_inserir_imagem_modelo_evento = new javax.swing.JLabel();
        jlbl_tela_fundo_modelo_evento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 612));
        setName("add_evento"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_codigo_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_codigo_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_codigo_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_codigo_modelo_evento.setText("CÓDIGO");
        getContentPane().add(jlbl_codigo_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 128, -1, -1));

        jtxtf_codigo_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_codigo_modelo_evento.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jtxtf_codigo_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_codigo_modelo_evento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtf_codigo_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        jtxtf_codigo_modelo_evento.setPreferredSize(new java.awt.Dimension(64, 25));
        getContentPane().add(jtxtf_codigo_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 140, -1, -1));

        jlbl_nome_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_nome_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_nome_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_nome_modelo_evento.setText("NOME MODELO");
        getContentPane().add(jlbl_nome_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 168, -1, -1));

        jtxtf_nome_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_nome_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_nome_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_nome_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_nome_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 290, 25));

        jlbl_coordenador_esponsavel.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_coordenador_esponsavel.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_coordenador_esponsavel.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_coordenador_esponsavel.setText("COORDENADOR RESPONSÁVEL");
        getContentPane().add(jlbl_coordenador_esponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 206, -1, -1));

        jtxtf_coordenador_responsavel.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_coordenador_responsavel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_coordenador_responsavel.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_coordenador_responsavel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_coordenador_responsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 218, 290, 25));

        jlbl_Contato.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_Contato.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_Contato.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_Contato.setText("CONTATO");
        getContentPane().add(jlbl_Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 242, -1, -1));

        jtxtf_Contato.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_Contato.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_Contato.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 254, 140, 25));

        jlbl_Publico.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_Publico.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_Publico.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_Publico.setText("PUBLICO");
        getContentPane().add(jlbl_Publico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jcbx_Publico.setBackground(new java.awt.Color(255, 255, 255));
        jcbx_Publico.setEditable(true);
        jcbx_Publico.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbx_Publico.setForeground(new java.awt.Color(135, 79, 255));
        jcbx_Publico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANIVERSÁRIO", "ANIVERSÁRIO KIDS", "BAILÉ", "CASAMENTO", "CHÁ DE BEBÊ", "CHÁ DE CASA NOVA", "CHÁ REVELAÇÃO", "DEBUTANTE", "DIA DAS MÃES", "DIA DOS PAIS", "DIA DOS NAMORADOS", "ENCONTRO", "EUCARISTIA", "FORMATURA", "NOIVADO", "OUTROS", " " }));
        jcbx_Publico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        jcbx_Publico.setPreferredSize(new java.awt.Dimension(165, 19));
        jcbx_Publico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_PublicoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbx_Publico, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 294, 140, 25));

        jlbl_locais_de_realizacao.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_locais_de_realizacao.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_locais_de_realizacao.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_locais_de_realizacao.setText("TIPO DE LOCAL");
        getContentPane().add(jlbl_locais_de_realizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        jcbx_locais_de_realizacao.setBackground(new java.awt.Color(255, 255, 255));
        jcbx_locais_de_realizacao.setEditable(true);
        jcbx_locais_de_realizacao.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbx_locais_de_realizacao.setForeground(new java.awt.Color(135, 79, 255));
        jcbx_locais_de_realizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro de convenções", "Cerimonial", "Casa de festas", "Salão de festas", "Restaurante", "Bar", "Hotel", "Auditório", "Resort", "Camping", "Sítio", "Chacara", "Fazenda", "Centro comunitário", "Club" }));
        jcbx_locais_de_realizacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        jcbx_locais_de_realizacao.setPreferredSize(new java.awt.Dimension(165, 19));
        jcbx_locais_de_realizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_locais_de_realizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbx_locais_de_realizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 332, 140, 25));

        jlbl_Dt_Inicial.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_Dt_Inicial.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_Dt_Inicial.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_Dt_Inicial.setText("DATA DE INICIO");
        getContentPane().add(jlbl_Dt_Inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 360, -1, -1));

        jtxtf_Dt_Inicial.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_Dt_Inicial.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_Dt_Inicial.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_Dt_Inicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_Dt_Inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 372, 140, 25));

        jlbl_Dt_Termino.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_Dt_Termino.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_Dt_Termino.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_Dt_Termino.setText("DATA DE TÉRMINO");
        getContentPane().add(jlbl_Dt_Termino, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 360, -1, -1));

        jtxtf_Dt_Termino.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_Dt_Termino.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_Dt_Termino.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_Dt_Termino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_Dt_Termino, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 372, 140, 25));

        jlbl_descricao_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_descricao_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_descricao_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_descricao_modelo_evento.setText("DESCRIÇÃO");
        getContentPane().add(jlbl_descricao_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 168, 50, -1));

        jtxta_descricao_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxta_descricao_modelo_evento.setColumns(20);
        jtxta_descricao_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxta_descricao_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxta_descricao_modelo_evento.setRows(5);
        jtxta_descricao_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        jtxta_descricao_modelo_evento.setMinimumSize(null);
        jtxta_descricao_modelo_evento.setName(""); // NOI18N
        jtxta_descricao_modelo_evento.setPreferredSize(new java.awt.Dimension(162, 70));
        jsclp_Descricao.setViewportView(jtxta_descricao_modelo_evento);

        getContentPane().add(jsclp_Descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 300, 180));

        jlbl_logradouro_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_logradouro_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_logradouro_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_logradouro_modelo_evento.setText("LOGRADOURO");
        getContentPane().add(jlbl_logradouro_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 398, -1, -1));

        jtxtf_logradouro_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_logradouro_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_logradouro_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_logradouro_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_logradouro_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 270, 25));

        jlbl_numero_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_numero_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_numero_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_numero_modelo_evento.setText("NÚMERO");
        getContentPane().add(jlbl_numero_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 398, -1, -1));

        jtxtf_numero_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_numero_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_numero_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_numero_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_numero_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 70, 25));

        jlbl_complemento_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_complemento_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_complemento_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_complemento_modelo_evento.setText("COMPLEMENTO");
        getContentPane().add(jlbl_complemento_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 398, -1, -1));

        jtxtf_complemento_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_complemento_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_complemento_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_complemento_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_complemento_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 239, 25));

        jlbl_bairro_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_bairro_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_bairro_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_bairro_modelo_evento.setText("LOCALIZAÇÃO");
        getContentPane().add(jlbl_bairro_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 438, -1, -1));

        jtxtf_bairro_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_bairro_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_bairro_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_bairro_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_bairro_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 210, 25));

        jlbl_cidade_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_cidade_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_cidade_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_cidade_modelo_evento.setText("CIDADE");
        getContentPane().add(jlbl_cidade_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 438, -1, -1));

        jtxtf_cidade_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_cidade_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_cidade_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_cidade_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_cidade_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 190, 25));

        jlbl_uf_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_uf_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_uf_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_uf_modelo_evento.setText("UF");
        getContentPane().add(jlbl_uf_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 438, -1, -1));

        jtxtf_uf_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_uf_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_uf_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_uf_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_uf_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 40, 25));

        jlbl_cep_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_cep_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_cep_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_cep_modelo_evento.setText("CEP");
        getContentPane().add(jlbl_cep_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 438, -1, -1));

        jtxtf_cep_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_cep_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_cep_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_cep_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_cep_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 130, 25));

        jlbl_img_logo_EF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        getContentPane().add(jlbl_img_logo_EF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, -1, -1));

        jlbl_txt_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_txt_modelo_evento.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_txt_modelo_evento.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_txt_modelo_evento.setText("MODELO");
        getContentPane().add(jlbl_txt_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 60));
        getContentPane().add(jlbl_img_txt_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 310, -1));

        jlbl_txt_de_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_txt_de_evento.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        jlbl_txt_de_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_txt_de_evento.setText("DE EVENTO");
        getContentPane().add(jlbl_txt_de_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 22, 260, 60));

        jlbl_btn_excluir_modelo_evento.setToolTipText("");
        getContentPane().add(jlbl_btn_excluir_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        jlbl_btn_buscar_modelo_evento.setToolTipText("");
        getContentPane().add(jlbl_btn_buscar_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        jlbl_qtd_participante.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_qtd_participante.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_qtd_participante.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_qtd_participante.setText("QTD PARTICIPANTES");
        getContentPane().add(jlbl_qtd_participante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jcbx_qtd_participante.setBackground(new java.awt.Color(255, 255, 255));
        jcbx_qtd_participante.setEditable(true);
        jcbx_qtd_participante.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbx_qtd_participante.setForeground(new java.awt.Color(135, 79, 255));
        jcbx_qtd_participante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "25 até 50", "50 até 75", "75 até 100", "100 até 125", "125 até 150", "150 até 175", "175 até 200", "200 até 225", "225 até 250", "250 até 275", "275 até 300", " " }));
        jcbx_qtd_participante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        jcbx_qtd_participante.setPreferredSize(new java.awt.Dimension(165, 19));
        jcbx_qtd_participante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_qtd_participanteActionPerformed(evt);
            }
        });
        getContentPane().add(jcbx_qtd_participante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 294, 140, 25));

        jlbl_itens_servicos.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_itens_servicos.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_itens_servicos.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_itens_servicos.setText("SERVIÇOS CONTRATADOS");
        getContentPane().add(jlbl_itens_servicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jcbx_itens_servicos.setBackground(new java.awt.Color(255, 255, 255));
        jcbx_itens_servicos.setEditable(true);
        jcbx_itens_servicos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbx_itens_servicos.setForeground(new java.awt.Color(135, 79, 255));
        jcbx_itens_servicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRODUTOS DESCARTAVEIS", "BEBIDAS", "COMIDAS", "SALGADOS", "SONORIZAÇÃO", "MULTIMIDEA", "ARRANJO", "DECORAÇÃO", "FLORICULTURA", "MESAS & CADEIRAS", "CERIMONIALISTA", "DJ", "GARÇON", "COZINHEIRO", "CHURRASQUEIRO", "BUFFET", "LIMPEZA", "HOSPEDAGEM", "LOGISTICA EM GERAL" }));
        jcbx_itens_servicos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        jcbx_itens_servicos.setPreferredSize(new java.awt.Dimension(165, 19));
        jcbx_itens_servicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbx_itens_servicosActionPerformed(evt);
            }
        });
        getContentPane().add(jcbx_itens_servicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 332, 140, 25));

        jlbl_local_modelo_evento.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jlbl_local_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_local_modelo_evento.setText("LOCAL");
        getContentPane().add(jlbl_local_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 368, -1, -1));

        jckb_c_local_modelo_evento1.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        jckb_c_local_modelo_evento1.setForeground(new java.awt.Color(135, 79, 255));
        jckb_c_local_modelo_evento1.setText("C/LOCAL");
        getContentPane().add(jckb_c_local_modelo_evento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 380, -1, -1));

        jckb_s_local_modelo_evento.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        jckb_s_local_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jckb_s_local_modelo_evento.setText("S/LOCAL");
        getContentPane().add(jckb_s_local_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jlbl_nome_local_modelo_evento.setBackground(new java.awt.Color(135, 79, 255));
        jlbl_nome_local_modelo_evento.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jlbl_nome_local_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_nome_local_modelo_evento.setText("NOME LOCAL");
        getContentPane().add(jlbl_nome_local_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        jtxtf_nome_local_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        jtxtf_nome_local_modelo_evento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtxtf_nome_local_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jtxtf_nome_local_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        getContentPane().add(jtxtf_nome_local_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 372, 140, 25));

        Jbtn_novo_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        Jbtn_novo_modelo_evento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Jbtn_novo_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        Jbtn_novo_modelo_evento.setLabel("Confirmar");
        Jbtn_novo_modelo_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_novo_modelo_eventoActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_novo_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        Jbtn_editar_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        Jbtn_editar_modelo_evento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Jbtn_editar_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        Jbtn_editar_modelo_evento.setLabel("Editar");
        Jbtn_editar_modelo_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_editar_modelo_eventoActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_editar_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        Jbtn_excluir_modelo_evento.setBackground(new java.awt.Color(255, 255, 255));
        Jbtn_excluir_modelo_evento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Jbtn_excluir_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        Jbtn_excluir_modelo_evento.setLabel("Excluir");
        Jbtn_excluir_modelo_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_excluir_modelo_eventoActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_excluir_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        jbtn_voltar_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_voltar_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltar.png"))); // NOI18N
        jbtn_voltar_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_voltar_dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_voltar_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 50, 30));

        jbtn_inserir_imagem_modelo_evento.setBackground(new java.awt.Color(132, 39, 205));
        jbtn_inserir_imagem_modelo_evento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtn_inserir_imagem_modelo_evento.setText("Inserir Img");
        jbtn_inserir_imagem_modelo_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_inserir_imagem_modelo_eventoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_inserir_imagem_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 370, -1, -1));
        getContentPane().add(jlbl_inserir_imagem_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 160, 180));

        jlbl_tela_fundo_modelo_evento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbl_tela_fundo_modelo_evento.setForeground(new java.awt.Color(135, 79, 255));
        jlbl_tela_fundo_modelo_evento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpnl_fundo.png"))); // NOI18N
        jlbl_tela_fundo_modelo_evento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 79, 255), 1, true));
        jlbl_tela_fundo_modelo_evento.setName("S/LOCAL");
        getContentPane().add(jlbl_tela_fundo_modelo_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbx_PublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_PublicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbx_PublicoActionPerformed

    private void Jbtn_novo_modelo_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_novo_modelo_eventoActionPerformed
        try {
            // TODO add your handling code here:
            Connection conexao = null;
            PreparedStatement statement= null;
            
            String url = "jdbc:mysql://127.0.0.1:3306/EventFlow";
            String user = "root";
            String password = "";
            
            conexao = DriverManager.getConnection(url, user, password);
            String sql = "INSERT INTO Evento(TituloEvento, Responsavel_Evento, Contato_Evento, DataEvento_inicial, DataEvento_Final, LocalEvento, HorarioEvento_inicial, HorarioEvento_Final, DescricaoEvento, TipoEvento) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            statement = conexao.prepareStatement(sql);
            statement.setString(1,jtxtf_nome_modelo_evento.getText());
            statement.setString(2, jtxtf_coordenador_responsavel.getText());
            statement.setInt(3, Integer.parseInt(jtxtf_Contato.getText()));
            statement.setInt(4, Integer.parseInt(jtxtf_Dt_Inicial.getText()));
            statement.setInt(5, Integer.parseInt(jtxtf_Dt_Termino.getText()));
            statement.setString(6, jtxtf_bairro_modelo_evento.getText());
            statement.setString(9, jtxta_descricao_modelo_evento.getText());
            statement.setString(10, jcbx_Publico.getSelectedItem().toString());
            
            System.out.println("Deu certo");
            JOptionPane.showMessageDialog(null, "Evento Cadastrado com sucesso!");
            statement.executeUpdate();
            
            modelo_evento.this.dispose();
            
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(modelo_evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Jbtn_novo_modelo_eventoActionPerformed

    private void jbtn_voltar_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_voltar_dashboardActionPerformed
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_voltar_dashboardActionPerformed

    private void jbtn_inserir_imagem_modelo_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_inserir_imagem_modelo_eventoActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Escolha uma imagem");

        // os tipos que eu vou permitir
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imagens", "jpg", "png"));

        // aqui eu estou mostrando o meu filechooser
        int userSelection = fileChooser.showOpenDialog(this);

        if(userSelection == JFileChooser.APPROVE_OPTION){
            File fileToUpload = fileChooser.getSelectedFile();
            System.out.println("Arquivo Selecionado: " + fileToUpload.getAbsolutePath());

            // só to garantindo que a minha JLabel tem um tamanho que seja maior que 0
            if(jlbl_inserir_imagem_modelo_evento.getWidth() > 0 && jlbl_inserir_imagem_modelo_evento.getHeight() > 0){

                //aqui eu consigo exibir a imagem
                ImageIcon imageIcon = new ImageIcon(fileToUpload.getAbsolutePath());
                Image image = imageIcon.getImage().getScaledInstance(jlbl_inserir_imagem_modelo_evento.getWidth(), jlbl_inserir_imagem_modelo_evento.getHeight(), Image.SCALE_SMOOTH);
                jlbl_inserir_imagem_modelo_evento.setIcon(new ImageIcon(image));
            }
            else{
                System.out.println("A sua jlabel tem altura ou largura igual a 0");
            }
        }
    }//GEN-LAST:event_jbtn_inserir_imagem_modelo_eventoActionPerformed

    private void Jbtn_editar_modelo_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_editar_modelo_eventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_editar_modelo_eventoActionPerformed

    private void Jbtn_excluir_modelo_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_excluir_modelo_eventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_excluir_modelo_eventoActionPerformed

    private void jcbx_locais_de_realizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_locais_de_realizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbx_locais_de_realizacaoActionPerformed

    private void jcbx_qtd_participanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_qtd_participanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbx_qtd_participanteActionPerformed

    private void jcbx_itens_servicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbx_itens_servicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbx_itens_servicosActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modelo_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modelo_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modelo_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modelo_evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modelo_evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Jbtn_editar_modelo_evento;
    private java.awt.Button Jbtn_excluir_modelo_evento;
    private java.awt.Button Jbtn_novo_modelo_evento;
    private javax.swing.JToggleButton jbtn_inserir_imagem_modelo_evento;
    private javax.swing.JButton jbtn_voltar_dashboard;
    private javax.swing.JComboBox<String> jcbx_Publico;
    private javax.swing.JComboBox<String> jcbx_itens_servicos;
    private javax.swing.JComboBox<String> jcbx_locais_de_realizacao;
    private javax.swing.JComboBox<String> jcbx_qtd_participante;
    private javax.swing.JCheckBox jckb_c_local_modelo_evento1;
    private javax.swing.JCheckBox jckb_s_local_modelo_evento;
    private javax.swing.JLabel jlbl_Contato;
    private javax.swing.JLabel jlbl_Dt_Inicial;
    private javax.swing.JLabel jlbl_Dt_Termino;
    private javax.swing.JLabel jlbl_Publico;
    private javax.swing.JLabel jlbl_bairro_modelo_evento;
    private javax.swing.JLabel jlbl_btn_buscar_modelo_evento;
    private javax.swing.JLabel jlbl_btn_excluir_modelo_evento;
    private javax.swing.JLabel jlbl_cep_modelo_evento;
    private javax.swing.JLabel jlbl_cidade_modelo_evento;
    private javax.swing.JLabel jlbl_codigo_modelo_evento;
    private javax.swing.JLabel jlbl_complemento_modelo_evento;
    private javax.swing.JLabel jlbl_coordenador_esponsavel;
    private javax.swing.JLabel jlbl_descricao_modelo_evento;
    private javax.swing.JLabel jlbl_img_logo_EF;
    private javax.swing.JLabel jlbl_img_txt_modelo_evento;
    private javax.swing.JLabel jlbl_inserir_imagem_modelo_evento;
    private javax.swing.JLabel jlbl_itens_servicos;
    private javax.swing.JLabel jlbl_locais_de_realizacao;
    private javax.swing.JLabel jlbl_local_modelo_evento;
    private javax.swing.JLabel jlbl_logradouro_modelo_evento;
    private javax.swing.JLabel jlbl_nome_local_modelo_evento;
    private javax.swing.JLabel jlbl_nome_modelo_evento;
    private javax.swing.JLabel jlbl_numero_modelo_evento;
    private javax.swing.JLabel jlbl_qtd_participante;
    private javax.swing.JLabel jlbl_tela_fundo_modelo_evento;
    private javax.swing.JLabel jlbl_txt_de_evento;
    private javax.swing.JLabel jlbl_txt_modelo_evento;
    private javax.swing.JLabel jlbl_uf_modelo_evento;
    private javax.swing.JScrollPane jsclp_Descricao;
    private javax.swing.JTextArea jtxta_descricao_modelo_evento;
    private javax.swing.JTextField jtxtf_Contato;
    private javax.swing.JTextField jtxtf_Dt_Inicial;
    private javax.swing.JTextField jtxtf_Dt_Termino;
    private javax.swing.JTextField jtxtf_bairro_modelo_evento;
    private javax.swing.JTextField jtxtf_cep_modelo_evento;
    private javax.swing.JTextField jtxtf_cidade_modelo_evento;
    private javax.swing.JTextField jtxtf_codigo_modelo_evento;
    private javax.swing.JTextField jtxtf_complemento_modelo_evento;
    private javax.swing.JTextField jtxtf_coordenador_responsavel;
    private javax.swing.JTextField jtxtf_logradouro_modelo_evento;
    private javax.swing.JTextField jtxtf_nome_local_modelo_evento;
    private javax.swing.JTextField jtxtf_nome_modelo_evento;
    private javax.swing.JTextField jtxtf_numero_modelo_evento;
    private javax.swing.JTextField jtxtf_uf_modelo_evento;
    // End of variables declaration//GEN-END:variables
}
